// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chirps.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createChirp = `-- name: CreateChirp :one
INSERT INTO chirps (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateChirpParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChirp, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteChirpByOwner = `-- name: DeleteChirpByOwner :execrows
DELETE FROM chirps
WHERE id = $1 AND user_id = $2
`

type DeleteChirpByOwnerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteChirpByOwner(ctx context.Context, arg DeleteChirpByOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChirpByOwner, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChirp = `-- name: GetChirp :one
SELECT id, created_at, updated_at, body, user_id FROM chirps
WHERE id = $1
`

func (q *Queries) GetChirp(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirp, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const listChirpsAsc = `-- name: ListChirpsAsc :many
SELECT id, created_at, updated_at, body, user_id FROM chirps
WHERE ($1::uuid IS NULL OR user_id = $1::uuid)
  AND ($2::timestamp IS NULL
       OR (created_at, id) > ($2::timestamp, $3::uuid))
ORDER BY created_at ASC, id ASC
LIMIT $4
`

type ListChirpsAscParams struct {
	AuthorID        uuid.NullUUID
	CursorCreatedAt sql.NullTime
	CursorID        uuid.NullUUID
	RowLimit        int32
}

// Keyset pagination: rows strictly after (cursor_created_at, cursor_id).
func (q *Queries) ListChirpsAsc(ctx context.Context, arg ListChirpsAscParams) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, listChirpsAsc,
		arg.AuthorID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChirpsDesc = `-- name: ListChirpsDesc :many
SELECT id, created_at, updated_at, body, user_id FROM chirps
WHERE ($1::uuid IS NULL OR user_id = $1::uuid)
  AND ($2::timestamp IS NULL
       OR (created_at, id) < ($2::timestamp, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListChirpsDescParams struct {
	AuthorID        uuid.NullUUID
	CursorCreatedAt sql.NullTime
	CursorID        uuid.NullUUID
	RowLimit        int32
}

func (q *Queries) ListChirpsDesc(ctx context.Context, arg ListChirpsDescParams) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, listChirpsDesc,
		arg.AuthorID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
